cameras:
    perspective:
        type: perspective
        focal_length: [[16, 2], [17, 2.5], [18, 3], [19, 4], [20, 6]] # pairs of [zoom, focal len]
        vanishing_point: [0, -500] # relative to center of screen, in pixels
        active: true

lights:
    directional1:
        type: directional
        direction: [.1, .5, -1]
        diffuse: .2
        ambient: 1.1

scene:
    background:
        color: '#9dc3de'

styles:
    flat:
        base: polygons
        lighting: false

    flat_lines:
        base: lines
        lighting: false

    buildings:
        base: polygons
        shaders:
            blocks:
                color: |
                    color.rgb = vec3(min((v_world_position.z*.0005 + .65),.8));

sources:
    osm:
        type: TopoJSONTiles
        url:  //vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=vector-tiles-HqUVidw

layers:
    earth:
        data: { source: osm }
        draw:
            polygons:
                style: flat
                order: 0
                color: '#f0ebeb'

    landuse:
        data: { source: osm }
        filter:
            name: true
            any:
                - { $zoom: { min: 9 }, area: { min: 10000000 } }
                - { $zoom: { min: 10 }, area: { min: 3300000 } }
                - { $zoom: { min: 12 }, area: { min: 1000000 } }
                - { $zoom: { min: 13 }, area: { min: 10000 } }
                - { $zoom: { min: 15 } }
        draw:
            polygons:
                order: 1
                style: flat
        green:
            filter: { kind: [park, graveyard, cemetery, forest, recreation_ground] }
            draw:
                polygons:
                    order: 2
                    color: '#bddec5'
        blue:
            filter: { kind: [commercial, industrial] }
            draw:
                polygons:
                    # color: '#6ea0a4'
                    color: '#C0CDCD'
        orange:
            filter: { kind: [university] }
            draw:
                polygons:
                    color: '#D9CFC3'

    water:
        data: { source: osm }
        filter:
            any:
                - { $zoom: { min: 0 }, area: { min: 10000000 } }
                - { $zoom: { min: 10 }, area: { min: 1000000 } }
                - { $zoom: { min: 12 }, area: { min: 100000 } }
                - { $zoom: { min: 15 }, area: { min: 1000 } }
                - { $zoom: { min: 18 } }
        draw:
            polygons:
                style: flat
                order: 3
                color: '#9dc3de'

    roads:
        data: { source: osm }
        filter:
            not: { kind: [rail] }
        draw:
            lines:
                style: flat_lines
                color: white
                width: 12
                order: function () { return feature.sort_key + 5; }
                outline:
                    color: [[16, '#999'], [18, '#aaa']]
                    width: [[15, 0], [16, 2]]
                    order: 4 # put all outlines below all roads (for now)

        rounded:
            filter: { $zoom: { min: 17 } }
            draw:
                lines:
                    join: round

        highway:
            filter: { kind: highway }
            draw:
                lines:
                    color: '#D16768'
                    width: [[14, 2px], [15, 12]]
                    outline:
                        width: [[14, 0], [15, 2]]
            link:
                filter: { is_link: yes }
                draw:
                    lines:
                        color: '#aaa'
                        width: [[13, 0], [14, 12]]
        major_road:
            filter: { kind: major_road, $zoom: { min: 10 } }
            draw:
                lines:
                    width: [[10, 0], [13, 2px], [14, 2px], [16, 12]]
                    outline:
                        width: [[16, 0], [17, 1]]
        minor_road:
            filter: { kind: minor_road }
            draw:
                lines:
                    width: [[13, 0px], [14, 1px], [15, 8]]
                    outline:
                        width: [[17, 0], [18, 1]]
        paths:
            filter: { kind: path }
            draw:
                lines:
                    color: '#bbb'
                    width: [[15, 0px], [18, 2px]]
                    order: 3
                    outline:
                        width: 0
        airports:
            filter: { aeroway: true }
            draw:
                lines:
                    color: '#ddd'
                    outline:
                        width: 0

            taxiways:
                filter: { aeroway: taxiway }
                draw:
                    lines:
                        width: [[13, 0px], [14, 2px], [17, 10px]]

            runways:
                filter: { aeroway: runway }
                draw:
                    lines:
                        color: [[13, '#FFE4B5'], [16, white]]
                        width: [[11, 3px], [12, 5px], [13, 10px], [15, 75]]
                        order: 39
                        cap: square
                        outline:
                            color: orange
                            width: [[11, 0px], [12, 1px], [13, 2px], [15, 12.5]]
                            order: 38

    buildings:
        data: { source: osm }
        filter: { $zoom: { min: 14 } }

        draw:
            polygons:
                order: 50
                color: [.65, .65, .65]

        # extrude 3d buildings
        extruded:
            filter: { $zoom: { min: 15 } }
            draw:
                polygons:
                    style: buildings
                    extrude: function () { return feature.height > 20 || $zoom >= 16; }

        high-line:
            # filter: { uid: "37054313" }
            filter: { roof_material: grass }
            draw:
                polygons:
                    style: flat
                    color: '#bddec5'

    road_labels:
        data: { source: osm, layer: roads }
        filter: { name: true, aeroway: false, tunnel: false, railway: false, not: { kind: rail } }

        highway:
            filter: { kind: highway, $zoom: { min: 7 } }
            draw:
                text:
                    font:
                        fill: '#666'
                        # size: 12pt
                        typeface: 100 12px Helvetica
                        stroke: { color: white, width: 4 }

        not_highway:
            filter: { not: { kind: highway }, $zoom: { min: 13 } }
            draw:
                text:
                    font:
                        fill: '#666'
                        stroke: { color: white, width: 4 }
                        typeface: 100 12px Helvetica

            major_road:
                filter: { kind: major_road, $zoom: { min: 14 } }
                draw:
                    text:
                        font:
                            typeface: 100 16px Helvetica
                            stroke: { color: white, width: 4 }
            minor_road:
                filter: { kind: minor_road, railway: false, $zoom: { min: 15 } }
                draw:
                    text:
                        font:
                            typeface: 100 12px Helvetica
                            stroke: { color: white, width: 4 }
            small:
                filter: { highway: [residential, unclassified], $zoom: { max: 15 } }
                visible: false

    poi_icons:
        data: { source: osm, layer: pois }
        filter: { name: true, not: { kind: [peak, viewpoint, bicycle_rental, car_sharing] }, $zoom: { min: 15 } }
        draw:
            points:
                color: darkred
                size: [[13, 8px], [15, 12px]]

    places:
        data: { source: osm }
        filter: { name: true, not: { kind: [county, state, island] } }
        draw:
            text:
                font:
                    typeface: italic 12pt Helvetica
                    fill: black
                    stroke: { color: white, width: 3 }
        minor-places:
            filter: { kind: [hamlet, village, town, neighbourhood, suburb, quarter], $zoom: { max: 13 } }
            visible: false

    landuse_labels:
        data: { source: osm }
        filter:
            name: true
            kind: [park, forest, cemetery, graveyard]
            any:
                - { $zoom: { min: 9 }, area: { min: 100000000 } }
                - { $zoom: { min: 10 }, area: { min: 10000000 } }
                - { $zoom: { min: 12 }, area: { min: 1000000 } }
                - { $zoom: { min: 15 }, area: { min: 10000 } }
                - { $zoom: { min: 18 } }
        draw:
            text:
                font:
                    typeface: Italic 10pt Lucida Grande
                    fill: darkgreen
                    stroke: { color: white, width: 3 }
